#OPENAI_API_KEY= "sk-proj-dvTjB6ArXxjL1mia877GT3BlbkFJdbiFhcqT5pV5nwSl0e7r"

#TIMESCALE_SERVICE_URL= "postgres://tsdbadmin:rbpold1dfluq73vz@na5atsc8p7.bg1tiecf3t.tsdb.cloud.timescale.com:31731/tsdb?sslmode=require"


#"postgres://tsdbadmin:lne10my8dt7b1rhv@eny2qgjth8.ax0en0061z.tsdb.cloud.timescale.com:37206/tsdb?sslmode=require"

ENABLE_LOAD=1

